### PR TITLE
Few fixes in sct_extract_metric and batch processing outputs

### LINKED ISSUE #1961: batch_processing: put back -qc output on the t2 segmentation with propseg
in [batch_processing](https://github.com/neuropoly/spinalcordtoolbox/blob/master/batch_processing.sh#L68), the flag `-qc "$SCT_BP_QC_FOLDER"` has been removed in recent commits. It should be put back in.

### LINKED ISSUE #1987: Recent modifications in extact_metric is altering batch_processing final output
Because of recent modifications merged to `master` branch, likely related to `sct_extract_metric`, the output of `batch_processing` needs fixup. It shows:
~~~
t2/CSA:   78.703221, 1.760750
mt/MTR:   2018/08/08 - 15:52:32,/home/jcohen/sct_example_data/mt/mtr.nii.gz,map,"2,3,4,5","15,16,17,11,12,13,14,8,9,10,4,5,6,7",51,white matter,980.883843843,54.1147920284,0
t2s/CSA_GM:   13.240696, 3.370950
t2s/CSA_WM:   65.202414, 3.112070
dmri/FA:  2018/08/08 - 15:57:04,/home/jcohen/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",4,WM left lateral corticospinal tract,80.5077761052,0.758846851538,0.167810495669
dmri/FA:  2018/08/08 - 15:57:04,/home/jcohen/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",5,WM right lateral corticospinal tract,81.3368825917,0.785060184288,0.143668976472
~~~

instead of (v3.2.3):
~~~
t2/CSA:   78.182308, 1.762403
mt/MTR:   51, white matter, 1547.984915, 55.426165, 0.000000
t2s/CSA_GM:   13.282941, 3.440752
t2s/CSA_WM:   65.160860, 3.175766
dmri/FA:  4, WM left lateral corticospinal tract, 81.115248, 0.755613, 0.174256
dmri/FA:  5, WM right lateral corticospinal tract, 81.458362, 0.783391, 0.145285
~~~

Note: don't pay attention to the differences in results. This is another issue.

### PR DESCRIPTION
**Pull request by jcohenadad**
This PR brings a few cosmetic updates:
- Fixes #1987: `batch_processing` final output caused by recent modifications on `sct_extract_metric`
- Fixes #1961: Now running QC on the t2 segmentation with propseg

In addition, `sct_extract_metric` had to be modified because of some recently-introduced bugs in relation to the `perslice` and `perlevel` flags. Moreover, the separation of slice and levels is now done using ";" instead of ",", for better parsing of CSV output. 

Note to @zougloub: the current implementation/fix in `sct_extract_metric` might cause you a heart attack, but this is only a temporary bandage. Full healing will be provided by #1931.

### CODE REVIEW

File: batch_processing.sh [hunk 1]
```diff
@@ -247,11 +247,11 @@ cd ..
...
 echo
 echo "t2/CSA:  " `grep -v '^#' t2/csa_mean.txt | grep -v '^$'`
-echo "mt/MTR:  " `grep -v '^#' mt/mtr_in_wm.txt | grep -v '^$'`
+echo "mt/MTR(WM):  " `awk -F"," ' {print $9}' mtr_in_wm.txt | tail -1`
 echo "t2s/CSA_GM:  " `grep -v '^#' t2s/csa_gm/csa_mean.txt | grep -v '^$'`
 echo "t2s/CSA_WM:  " `grep -v '^#' t2s/csa_wm/csa_mean.txt | grep -v '^$'`
-echo "dmri/FA: " `grep -v '^#' dmri/fa_in_cst.txt | grep -v 'right'`
-echo "dmri/FA: " `grep -v '^#' dmri/fa_in_cst.txt | grep -v 'left'`
+echo "dmri/FA(CST_r): " `awk -F"," ' {print $9}' dmri/fa_in_cst.txt | tail -1`
+echo "dmri/FA(CST_l): " `awk -F"," ' {print $9}' dmri/fa_in_cst.txt | tail -2 | head -1`
```
Comment (zougloub) [inline batch_processing.sh]: Should get over unstructured data and these crazy awk/head/tail at some point...
